<template>
  <div class="home">
    <div class="home--hero">
      <h1>Hey, its me, the same design as everyhere else</h1>
      <p>Except I am a static site generated by google drive</p>
    </div>
    <div class="home--info">
      <h3>What makes this website special?</h3>
      <div class="hipster-spacer"></div>
      <p>So what, this site is a "static site", bit woop.... well, get ready to have your socks blown back to the midwest state you are from, this site uses google drive as its cms... yea, thats right, you know that tool you write all your blogposts in, then copy and paste them into your other cms, we use that. Grab your socks... I'll wait</p>
      <p>Thats right, static site built with google drive.</p>
    </div>

    <div class="home--post-container">
      <article class="home--post" v-for="post in posts">
        <div class="home--post-image" :style="{background: backgroundUrl(Math.random())}"></div>
        <div class="home--post-content">
          <h4>
            <router-link :to="post.path">{{ post.frontmatter.Title }}</router-link>
          </h4>

          <p>{{ post.frontmatter.Description }}</p>

          <p><router-link :to="post.path">Read more</router-link></p>
        </div>
      </article>
    </div>
  </div>
</template>

<script>
 export default {
     computed: {
         data () {
             return this.$page.frontmatter
         },
         actionLink () {
             return {
                 link: this.data.actionLink,
                 text: this.data.actionText
             }
         },
         posts() {
             return this.$site.pages
                        .filter(x => x.path.startsWith('/') && !x.frontmatter.blog_index)
                        .sort((a, b) => new Date(b.frontmatter.Date.replace(/\\/g,  "")) - new Date(a.frontmatter.Date.replace(/\\/g,  "")));
         }

     },
     methods:{
         backgroundUrl(rng){
             return "url('https://picsum.photos/500/200?random=" + Math.floor(rng*20) + "')"
         }
     }

 }
</script>

<style>
 .home--hero{
     width: 100%;
     height: 100vh;
     background: url("/unsplash-bg.jpg") no-repeat center center fixed;
     background-size: cover;
     display:flex;
     align-items:center;
     justify-content: center;
     flex-direction: column;
     color: #fff;
 }

 .home--hero h1{
     color: #fff;
 }
 .hipster-spacer{
     min-height: 3px;
     width: 7%;
     background-color: #336699;
 }
 .home--info .hipster-spacer{background-color: #fff}
 .home--info{
     display:flex;
     flex-direction:column;
     align-items: center;
     justify-content: center;
     color: #fff;
     background: #336699;
     height: 300px;
     box-sizing:border-box;
     padding: 10% 10% 13% 10%;
 }
 .home--info h3{margin-top: 0;}
 .home--info p{text-align: center;}
 .home--post-container{
     width: 90%;
     margin: -30px auto 0 auto;
     display: flex;
     flex-wrap: wrap;
     justify-content:space-between

 }
 .home--post{
     flex: 1 1 300px;
     background: #fff;
     box-sizing:border-box;
     border-radius: 4px;
     box-shadow: 1px 3px 8px rgba(39,44,49,.03);
     margin: 0 20px 40px 20px;
 }
 .home--post-content{
     margin:15px;
 }
 .home--post .home--post-image{
     background: url("https://picsum.photos/200/300");
     width: auto;
     height: 200px;
     background-size:cover;

 }
 .home--post:nth-child(12n+3){
     flex: 1 1 100%;
     display:flex;
     height: 240px;
 }

 .home--post:nth-child(12n+3) .home--post-image{
     width:100%;
     height:100%;
 }
.home--post:nth-child(12n+3) .home--post-content{width: 50%;}

.home--post h4 > a{
     text-decoration:none;
     color: #333;
 }
 .home--post p {
     font-size: 15px;
     font-weight: 400;
     font-family: Georgia,sans-serif;
     color: #15171a;

 }


</style>
